{"pwd" => "print working directory", "hostname" => "my computer's network name", "mkdir" => "make directory", 
	"cd" => "change directory", "ls" => "list directory", "rmdir" => "remove directory", "pushd" => "push directory", 
	"popd" => "pop directory", "cp" => "copy directory", "mv" => "move a file or directory", 
	"less" => "page through a file", "cat" => "print the whole file", "xargs" => "execute arguments", 
	"find" => "find files", "grep" => "find things inside files", "man" => "read a manual page", 
	"apropos" => "find what man page is appropriate", "env" => "look at your environment", 
	"echo" => "print some arguments", "export" => "export/set a new environment variable", 
	"exit" => "exit the shell", "sudo" => "DANGER! become super root user root DANGER!", 
	"chmod" => "change permission modifiers", "chown" => "change ownership",
	"$|$" => "Takes the output from the left command and pipes it to the command on the right", 
	"$<$" => "sends input from the right to the program or command on the left", 
	"$>$" => "takes the output of the command on the left and writes it to the file on the right", 
	"$>>$" => "takes the output of the command on the left and appends it to the right"}